training dataset
rnd4u-org/2021-knu-chatbot pull request #68
Opened 2021-02-08 19:12 UTC by liviiaaaa

2021-02-09 10:23 UTC, mVad requested changes

2021-02-09 10:23 UTC, mVad commented on task8.csv
> +entities:Project;;;what license does the <A> project have;select ?a where { <A> terms:license ?a };select distinct ?a { ?a terms:license [] }
Последняя колонка, запрос не верный во всех строках:
select distinct ?a { ?a terms:lisense [] } -> упущено WHERE

2021-02-11 15:12 UTC, mVad commented on task8.csv
> +entities:Repository;;;is <B> contributor involved to the <A> repository;ask ?a where { <A> terms:contributor <B> };select distinct ?a ?b where { ?a terms:contributor ?b }
Если используете два подставления, нужно заполнять и первую и третью колонку.
Или же вовсе их не заполнять, но указать в запросах генерации их тип

2021-02-12 12:35 UTC, liviiaaaa commented
Датасет оновила. Показник bleu 73.6 на 20000 епох

2021-02-14 18:58 UTC, merged